# Your COCO classes
coco_dict = {
        183: "unlabeled",
        1: "person",
        2: "bicycle",
        3: "car",
        4: "motorcycle",
        5: "airplane",
        6: "bus",
        7: "train",
        8: "truck",
        9: "boat",
        10: "traffic light",
        11: "fire hydrant",
        12: "street sign",
        13: "stop sign",
        14: "parking meter",
        15: "bench",
        16: "bird",
        17: "cat",
        18: "dog",
        19: "horse",
        20: "sheep",
        21: "cow",
        22: "elephant",
        23: "bear",
        24: "zebra",
        25: "giraffe",
        26: "hat",
        27: "backpack",
        28: "umbrella",
        29: "shoe",
        30: "eye glasses",
        31: "handbag",
        32: "tie",
        33: "suitcase",
        34: "frisbee",
        35: "skis",
        36: "snowboard",
        37: "sports ball",
        38: "kite",
        39: "baseball bat",
        40: "baseball glove",
        41: "skateboard",
        42: "surfboard",
        43: "tennis racket",
        44: "bottle",
        45: "plate",
        46: "wine glass",
        47: "cup",
        48: "fork",
        49: "knife",
        50: "spoon",
        51: "bowl",
        52: "banana",
        53: "apple",
        54: "sandwich",
        55: "orange",
        56: "broccoli",
        57: "carrot",
        58: "hot dog",
        59: "pizza",
        60: "donut",
        61: "cake",
        62: "chair",
        63: "couch",
        64: "potted plant",
        65: "bed",
        66: "mirror",
        67: "dining table",
        68: "window",
        69: "desk",
        70: "toilet",
        71: "door",
        72: "tv",
        73: "laptop",
        74: "mouse",
        75: "remote",
        76: "keyboard",
        77: "cell phone",
        78: "microwave",
        79: "oven",
        80: "toaster",
        81: "sink",
        82: "refrigerator",
        83: "blender",
        84: "book",
        85: "clock",
        86: "vase",
        87: "scissors",
        88: "teddy bear",
        89: "hair drier",
        90: "toothbrush",
        91: "hair brush",
        92: "banner",
        93: "blanket",
        94: "branch",
        95: "bridge",
        96: "building-other",
        97: "bush",
        98: "cabinet",
        99: "cage",
        100: "cardboard",
        101: "carpet",
        102: "ceiling-other",
        103: "ceiling-tile",
        104: "cloth",
        105: "clothes",
        106: "clouds",
        107: "counter",
        108: "cupboard",
        109: "curtain",
        110: "desk-stuff",
        111: "dirt",
        112: "door-stuff",
        113: "fence",
        114: "floor-marble",
        115: "floor-other",
        116: "floor-stone",
        117: "floor-tile",
        118: "floor-wood",
        119: "flower",
        120: "fog",
        121: "food-other",
        122: "fruit",
        123: "furniture-other",
        124: "grass",
        125: "gravel",
        126: "ground-other",
        127: "hill",
        128: "house",
        129: "leaves",
        130: "light",
        131: "mat",
        132: "metal",
        133: "mirror-stuff",
        134: "moss",
        135: "mountain",
        136: "mud",
        137: "napkin",
        138: "net",
        139: "paper",
        140: "pavement",
        141: "pillow",
        142: "plant-other",
        143: "plastic",
        144: "platform",
        145: "playingfield",
        146: "railing",
        147: "railroad",
        148: "river",
        149: "road",
        150: "rock",
        151: "roof",
        152: "rug",
        153: "salad",
        154: "sand",
        155: "sea",
        156: "shelf",
        157: "sky-other",
        158: "skyscraper",
        159: "snow",
        160: "solid-other",
        161: "stairs",
        162: "stone",
        163: "straw",
        164: "structural-other",
        165: "table",
        166: "tent",
        167: "textile-other",
        168: "towel",
        169: "tree",
        170: "vegetable",
        171: "wall-brick",
        172: "wall-concrete",
        173: "wall-other",
        174: "wall-panel",
        175: "wall-stone",
        176: "wall-tile",
        177: "wall-wood",
        178: "water-other",
        179: "waterdrops",
        180: "window-blind",
        181: "window-other",
        182: "wood"
    }


# Your ADE20K classes
ade_classes = {
    "wall": 1,
    "building": 2,
    "sky": 3,
    "floor": 4,
    "tree": 5,
    "ceiling": 6,
    "road": 7,
    "bed": 8,
    "window": 9,
    "grass": 10,
    "cabinet": 11,
    "sidewalk": 12,
    "person": 13,
    "earth": 14,
    "door": 15,
    "table": 16,
    "mountain": 17,
    "plant": 18,
    "curtain": 19,
    "chair": 20,
    "car": 21,
    "water": 22,
    "painting": 23,
    "sofa": 24,
    "shelf": 25,
    "house": 26,
    "sea": 27,
    "mirror": 28,
    "rug": 29,
    "field": 30,
    "armchair": 31,
    "seat": 32,
    "fence": 33,
    "desk": 34,
    "rock": 35,
    "wardrobe": 36,
    "lamp": 37,
    "bathtub": 38,
    "railing": 39,
    "cushion": 40,
    "base": 41,
    "box": 42,
    "column": 43,
    "signboard": 44,
    "chest of drawers": 45,
    "counter": 46,
    "sand": 47,
    "sink": 48,
    "skyscraper": 49,
    "fireplace": 50,
    "refrigerator": 51,
    "grandstand": 52,
    "path": 53,
    "stairs": 54,
    "runway": 55,
    "case": 56,
    "pool table": 57,
    "pillow": 58,
    "screen door": 59,
    "stairway": 60,
    "river": 61,
    "bridge": 62,
    "bookcase": 63,
    "blind": 64,
    "coffee table": 65,
    "toilet": 66,
    "flower": 67,
    "book": 68,
    "hill": 69,
    "bench": 70,
    "countertop": 71,
    "stove": 72,
    "palm": 73,
    "kitchen island": 74,
    "computer": 75,
    "swivel chair": 76,
    "boat": 77,
    "bar": 78,
    "arcade machine": 79,
    "hovel": 80,
    "bus": 81,
    "towel": 82,
    "light": 83,
    "truck": 84,
    "tower": 85,
    "chandelier": 86,
    "awning": 87,
    "streetlight": 88,
    "booth": 89,
    "television receiver": 90,
    "airplane": 91,
    "dirt track": 92,
    "apparel": 93,
    "pole": 94,
    "land": 95,
    "bannister": 96,
    "escalator": 97,
    "ottoman": 98,
    "bottle": 99,
    "buffet": 100,
    "poster": 101,
    "stage": 102,
    "van": 103,
    "ship": 104,
    "fountain": 105,
    "conveyor belt": 106,
    "canopy": 107,
    "washer": 108,
    "plaything": 109,
    "swimming pool": 110,
    "stool": 111,
    "barrel": 112,
    "basket": 113,
    "waterfall": 114,
    "tent": 115,
    "bag": 116,
    "minibike": 117,
    "cradle": 118,
    "oven": 119,
    "ball": 120,
    "food": 121,
    "step": 122,
    "tank": 123,
    "trade name": 124,
    "microwave": 125,
    "pot": 126,
    "animal": 127,
    "bicycle": 128,
    "lake": 129,
    "dishwasher": 130,
    "screen": 131,
    "blanket": 132,
    "sculpture": 133,
    "hood": 134,
    "sconce": 135,
    "vase": 136,
    "traffic light": 137,
    "tray": 138,
    "ashcan": 139,
    "fan": 140,
    "pier": 141,
    "crt screen": 142,
    "plate": 143,
    "monitor": 144,
    "bulletin board": 145,
    "shower": 146,
    "radiator": 147,
    "glass": 148,
    "clock": 149,
    "flag": 150,
}
# Create a reverse mapping from ADE20K class indices to names
ade_index_to_name = {v: k for k, v in ade_classes.items()}
ade_index_to_name[151] = 'other'
ade_full_classes = {
    "wall": "wall",
    "building": "building, edifice",
    "sky": "sky",
    "floor": "floor, flooring",
    "tree": "tree",
    "ceiling": "ceiling",
    "road": "road, route",
    "bed": "bed",
    "window": "windowpane, window",
    "grass": "grass",
    "cabinet": "cabinet",
    "sidewalk": "sidewalk, pavement",
    "person": "person, individual, someone, somebody, mortal, soul",
    "earth": "earth, ground",
    "door": "door, double door",
    "table": "table",
    "mountain": "mountain, mount",
    "plant": "plant, flora, plant life",
    "curtain": "curtain, drape, drapery, mantle, pall",
    "chair": "chair",
    "car": "car, auto, automobile, machine, motorcar",
    "water": "water",
    "painting": "painting, picture",
    "sofa": "sofa, couch, lounge",
    "shelf": "shelf",
    "house": "house",
    "sea": "sea",
    "mirror": "mirror",
    "rug": "rug, carpet, carpeting",
    "field": "field",
    "armchair": "armchair",
    "seat": "seat",
    "fence": "fence, fencing",
    "desk": "desk",
    "rock": "rock, stone",
    "wardrobe": "wardrobe, closet, press",
    "lamp": "lamp",
    "bathtub": "bathtub, bathing tub, bath, tub",
    "railing": "railing, rail",
    "cushion": "cushion",
    "base": "base, pedestal, stand",
    "box": "box",
    "column": "column, pillar",
    "signboard": "signboard, sign",
    "chest of drawers": "chest of drawers, chest, bureau, dresser",
    "counter": "counter",
    "sand": "sand",
    "sink": "sink",
    "skyscraper": "skyscraper",
    "fireplace": "fireplace, hearth, open fireplace",
    "refrigerator": "refrigerator, icebox",
    "grandstand": "grandstand, covered stand",
    "path": "path",
    "stairs": "stairs, steps",
    "runway": "runway",
    "case": "case, display case, showcase, vitrine",
    "pool table": "pool table, billiard table, snooker table",
    "pillow": "pillow",
    "screen door": "screen door, screen",
    "stairway": "stairway, staircase",
    "river": "river",
    "bridge": "bridge, span",
    "bookcase": "bookcase",
    "blind": "blind, screen",
    "coffee table": "coffee table, cocktail table",
    "toilet": "toilet, can, commode, crapper, pot, potty, stool, throne",
    "flower": "flower",
    "book": "book",
    "hill": "hill",
    "bench": "bench",
    "countertop": "countertop",
    "stove": "stove, kitchen stove, range, kitchen range, cooking stove",
    "palm": "palm, palm tree",
    "kitchen island": "kitchen island",
    "computer": "computer, computing machine, computing device, data processor, electronic computer, information processing system",
    "swivel chair": "swivel chair",
    "boat": "boat",
    "bar": "bar",
    "arcade machine": "arcade machine",
    "hovel": "hovel, hut, hutch, shack, shanty",
    "bus": "bus, autobus, coach, charabanc, double-decker, jitney, motorbus, motorcoach, omnibus, passenger vehicle",
    "towel": "towel",
    "light": "light, light source",
    "truck": "truck, motortruck",
    "tower": "tower",
    "chandelier": "chandelier, pendant, pendent",
    "awning": "awning, sunshade, sunblind",
    "streetlight": "streetlight, street lamp",
    "booth": "booth, cubicle, stall, kiosk",
    "television receiver": "television receiver, television, television set, tv, tv set, idiot box, boob tube, telly, goggle box",
    "airplane": "airplane, aeroplane, plane",
    "dirt track": "dirt track",
    "apparel": "apparel, wearing apparel, dress, clothes",
    "pole": "pole",
    "land": "land, ground, soil",
    "bannister": "bannister, banister, balustrade, balusters, handrail",
    "escalator": "escalator, moving staircase, moving stairway",
    "ottoman": "ottoman, pouf, pouffe, puff, hassock",
    "bottle": "bottle",
    "buffet": "buffet, counter, sideboard",
    "poster": "poster, posting, placard, notice, bill, card",
    "stage": "stage",
    "van": "van",
    "ship": "ship",
    "fountain": "fountain",
    "conveyor belt": "conveyor belt, conveyor",
    "canopy": "canopy",
    "washer": "washer, automatic washer, washing machine",
    "plaything": "plaything, toy",
    "swimming pool": "swimming pool, swimming bath, natatorium",
    "stool": "stool",
    "barrel": "barrel, cask",
    "basket": "basket, handbasket",
    "waterfall": "waterfall, falls",
    "tent": "tent, collapsible shelter",
    "bag": "bag",
    "minibike": "minibike, motorbike",
    "cradle": "cradle",
    "oven": "oven",
    "ball": "ball",
    "food": "food, solid food",
    "step": "step, stair",
    "tank": "tank, storage tank",
    "trade name": "trade name, brand name, brand, marque",
    "microwave": "microwave, microwave oven",
    "pot": "pot, flowerpot",
    "animal": "animal, animate being, beast, brute, creature, fauna",
    "bicycle": "bicycle, bike, wheel, cycle",
    "lake": "lake",
    "dishwasher": "dishwasher, dish washer, dishwashing machine",
    "screen": "screen, silver screen, projection screen",
    "blanket": "blanket, cover",
    "sculpture": "sculpture",
    "hood": "hood, exhaust hood",
    "sconce": "sconce",
    "vase": "vase",
    "traffic light": "traffic light, traffic signal, stoplight",
    "tray": "tray",
    "ashcan": "ashcan, trash can, garbage can, wastebin, ash bin, ash-bin, ashbin, dustbin, trash barrel, trash bin",
    "fan": "fan",
    "pier": "pier, wharf, wharfage, dock",
    "crt screen": "crt screen",
    "plate": "plate",
    "monitor": "monitor, monitoring device",
    "bulletin board": "bulletin board, notice board",
    "shower": "shower",
    "radiator": "radiator",
    "glass": "glass, drinking glass",
    "clock": "clock",
    "flag": "flag",
}
ade_full_class_to_name = {v: k for k, v in ade_full_classes.items()}
# print(ade_full_class_to_name)
# Create a mapping from COCO to ADE20K
# coco_to_ade_mapping = {coco_dict[key]: ade_classes[coco_dict[key]] for key in coco_dict if coco_dict[key] in ade_classes or coco_dict[key] in ade_full_class_to_name}
coco_to_ade_mapping = {}
ade_to_coco_mapping = {ade_classes[key]: coco_dict[ade_classes[key]] for key in ade_classes}
for key1 in ade_classes:
    for key2 in coco_dict:
        if key2 not in coco_to_ade_mapping:
            if coco_dict[key2] in ade_classes:
                coco_to_ade_mapping[key2] = ade_classes[coco_dict[key2]]
            elif key1 in coco_dict[key2]:
                coco_to_ade_mapping[key2] = ade_classes[key1]
            
            if 'baseball' in coco_dict[key2]:
                coco_to_ade_mapping[key2] = 151
            if 'car' in coco_dict[key2] and 'car' != coco_dict[key2]:
                coco_to_ade_mapping[key2] = 151
            if 'sandwich' in coco_dict[key2] or 'bush' in coco_dict[key2] or 'vegetable' in coco_dict[key2]:
                coco_to_ade_mapping[key2] = 151
for key1 in ade_classes:
    for key2 in coco_dict:
        if key2 not in coco_to_ade_mapping:
            coco_to_ade_mapping[key2] = 151

            
            
print(len(coco_to_ade_mapping))

# # Print the mapping
# for key, value in ade_to_coco_mapping.items():
#     print(f"ADE20K Class: {ade_index_to_name[key]} -> COCO Class: {value}")

final_coco_to_ade = {}
# Print the mapping
for key, value in coco_to_ade_mapping.items():
    final_coco_to_ade[key-1] = value - 1
    print(f"COCO Class: {coco_dict[key]} -> ADE20K Class: {ade_index_to_name[value]}")
# import json


# with open("data/coco_to_ade_mapping.json", "w") as file:
#     json.dump(final_coco_to_ade, file)

# with open("data/coco_to_ade_mapping.json", "r") as file:
#     loaded_dict = json.load(file)
# print(len(loaded_dict))
